name: space_invaders
description: A little space adventure.
version: 0.0.1
publish_to: none


environment:
  sdk: ^3.0.1
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.7.0
  provider: ^6.0.5
  audioplayers: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flame_audio: ^2.0.2

dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/explosion/
    - assets/images/player/
    - assets/images/enemy_0/
    - assets/images/background/
    - assets/images/money/
    - assets/audio/
