name: space_invaders
description: A little space adventure.
version: 0.0.0
publish_to: none


environment:
  sdk: ^2.17.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.7.0
  provider: ^6.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/explosion/
